### ISSUE TITLE
Error in installation command

### ISSUE THREAD

**Issue by cemuram** [AzureAD/microsoft-authentication-cli#129]
To apply variable expansion, this line
$url = 'https://raw.githubusercontent.com/AzureAD/microsoft-authentication-cli/${env:AZUREAUTH_VERSION}/install/install.ps1'

needs to be changed to (double quotes)
$url = "https://raw.githubusercontent.com/AzureAD/microsoft-authentication-cli/${env:AZUREAUTH_VERSION}/install/install.ps1"

**Comment by reillysiemens** [comment]
Hey, @cemuram, thanks for bringing this to our attention. Looks like this was a trivial oversight on our part. We'll fix this ASAP!

**Comment by reillysiemens** [comment]
Thanks again for the report, @cemuram. This should be fixed now. Holler if you still have any issues. 😄
