### ISSUE TITLE
Upgrade to the latest stable version of MSAL

### ISSUE THREAD

**Issue by reillysiemens** [AzureAD/microsoft-authentication-cli#133]
We briefly looked at upgrading MSAL versions in #82, but couldn't justify upgrading at the moment.

We do still want to upgrade MSAL versions, but after we've identified a version that delivers sufficient benefit and has been deployed long enough to guarantee some measure of stability.

This is a tracking issue to make sure we don't drop that task.

**Comment by goagain** [comment]
#323

**Comment by goagain** [comment]
#323 upgraded MSAL to latest stable version.
