### ISSUE TITLE
The option --cache=".IdentityService/msal_.cache ..." is not a valid absolute file path.

### ISSUE THREAD

**Issue by seanadams9** [AzureAD/microsoft-authentication-cli#174]
seanadams@Seans-MacBook-Pro ~ % azureauth
The --resource field or the --scope field is required.
The --client field is required.
The --tenant field is required.
The option --cache=`.IdentityService/msal_.cache` or environment varable AZUREAUTH_CACHE=`` is not a valid absolute file path.

Fresh install of 0.6.0, opened new terminal and ran azureauth with no params and got the error.

**Comment by mvanchaa** [comment]
Hey @seanadams9, we are fixing this issue - Refer #170 and will release it soon. Meanwhile, as a temporary workaround, make a ~/.local/share directory and try again.

`mdkir -p ~/.local/share`

**Comment by kyle-rader** [comment]
@seanadams9 We will be releasing in the next 1-2 weeks and the next version will contain the bugfix for this issue.

**Comment by kyle-rader-msft** [comment]
@seanadams9 AzureAuth 0.7.3 address this bug and you will find the matching internal library version is now available!
