### ISSUE TITLE
Change WS-Trust endpoint warning message

### ISSUE THREAD

**Issue by reillysiemens** [AzureAD/microsoft-authentication-cli#178]
The warning in this section of code introduced in #153 

https://github.com/AzureAD/microsoft-authentication-cli/blob/85a51c3c67e7d911a6a7471fcda26cf3b959dea3/src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs#L111-L114

could probably be more generic and refer to a non-Microsoft solution. How else could we phrase this?

**Comment by kyle-rader-msft** [comment]
@reillysiemens we could change "Corp Net" to something more generic like "corporate AD backed" networks. Though we should make sure it's accurate.
