### ISSUE TITLE
Is a prefix for prompt hint needed?

### ISSUE THREAD

**Issue by goagain** [AzureAD/microsoft-authentication-cli#24]
Here I think we should build a prompt hint to pass in, so that is always has `AzureAuth CLI` at the beginning. Perhaps a helper method to construct our prompt hint, that we can call here. 

Something like
```C#
private const string PromptHintPrefix = "Azure AUth CLI";
private string GetPromptHint() {
  if (string.IsNullOrEmpty(this.PromptHint) {
    return PromptHintPrefix;
  }
  else
  {
    return $"{PromptHintPrefix}: {this.PromptHint}";
  }
}
```

_Originally posted by @kyle-rader in https://github.com/AzureAD/microsoft-authentication-cli/pull/11#discussion_r849974649_

**Comment by reillysiemens** [comment]
From talking to some of our users it sounds like there's interest from them in better understanding where these authentication prompts are stemming from. One angle is to do what you've suggested here and add a well-known "`PromptHintPrefix`".

@kyle-rader also suggested that we could try to get the display name of the requested Azure resource and lean on that to establish further legitimacy.
