### ISSUE TITLE
Release url for 0.8.4 is broken

### ISSUE THREAD

**Issue by sopranopillow** [AzureAD/microsoft-authentication-cli#335]
Tried to install and was getting a 404 error. Looks like https://github.com/AzureAD/microsoft-authentication-cli/releases/tag/0.8.4 is broken.

**Comment by goagain** [comment]
@sopranopillow Sorry for the confusing. We were about to release 0.8.4 but suffered some issue. You can replace the version number with `0.8.3` temporarily.

**Comment by sopranopillow** [comment]
@goagain thanks, I did that, just wanted to give a heads up :)
