### ISSUE TITLE
Architecture parsing failing on MacOS with coreutils installed through Homebrew

### ISSUE THREAD

**Issue by zorfling** [AzureAD/microsoft-authentication-cli#350]
When trying to install the 1ES DevTool on MacOS and coreutils installed through Homebrew, I'm getting an error installing the azureauth cli that seems related to a bad parsing of `uname -a` in `install.sh`

`Error obtaining access token: [System.Exception: Error installing azureauth cli. Log: . Error: Unsupported architecture 'Darwin', unable to download a release`

Changing from `uname -a | rev | cut -d ' ' -f1 | rev` to grepping for `x86_64` or `arm64` seems to work - PR incoming

**Comment by reillysiemens** [comment]
@zorfling, thanks for bringing this to our attention! I should have assumed that `uname -a` wouldn't output stable columns. Using `grep` seems like a much safer approach. 👍

**Comment by reillysiemens** [comment]
Resolved this with #354 (a resubmission of @zorfling's #351).
