### ISSUE TITLE
Latest folder is a copy on Windows

### ISSUE THREAD

**Issue by marcelais** [AzureAD/microsoft-authentication-cli#47]
The installer creates a "latest" folder which corresponds to the most recent version of the auth tool.  On windows, this folder is a complete copy rather than a link.

While making a symbolic link requires administrator permission, creating a directory junction (`mklink /j latest v0.2.0`) does not and can be used here to avoid having a second copy of the tool.

**Comment by kyle-rader** [comment]
@marcelais that is fantastic to discover!

**Comment by reillysiemens** [comment]
This will be so much better than copying the whole directory. Thanks for pointing this out, @marcelais!

`mklink` seems to be a `cmd.exe` built-in, but we should be able to make directory junctions in PowerShell with
```PowerShell
New-Item -Path "C:\Absolute\path\to\latest" -Target "C:\Absolute\path\to\version" -ItemType Junction
```
